version: "3.3"

services:

  mapineq_postgres:
    container_name: mapineq_db
    build: ./sql/
    image: mapineq_postgis
    env_file: .env
    shm_size: '1gb'
    build:
      dockerfile: ./Dockerfile
      context: ./sql/
    volumes:
      - mapineq-db:/db/data
      - ./sql/postgresql.conf:/db/postgresql.conf
      - ./sql/init_data:/var/lib/postgresql/init_data
      - ./sql/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh
    networks:
      - mapineq_net
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  mapineq-db:

networks:
  mapineq_net:
