services:

  mapineq_postgres:
    container_name: mapineq_db
    image: mapineq_postgres
    env_file: .env
    shm_size: '1gb'
    build:
      dockerfile: ./Dockerfile
      context: ./
    volumes:
      - mapineq-db:/db/data
      - ./postgresql.conf:/db/postgresql.conf
      - ./db-init/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "config_file=/db/postgresql.conf" ]
    restart: unless-stopped

volumes:
  mapineq-db:
