name: Build dev Docker image and push to registry

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --tag registry.webhosting.rug.nl/mapineq/${{ github.ref_name }}mapineqfrontend:latest --file ./src/dashboard/app/Dockerfiledev
    - name: push image to registry
      run: |
          docker login -u p149377  -p ${{ secrets.REGISTRY_PASSWORD }} registry.webhosting.rug.nl
          docker push registry.webhosting.rug.nl/mapineq/${{ github.ref_name }}mapineqfrontend:latest
